ngpus: 2
nnodes: 1
tokens: 4   # this is the number of tokens in the vocabulary (nucleotides - A, C, G, T)
training:
  batch_size: 256
  accum: 1
  n_iters: 2000000
  snapshot_freq: 50000
  log_freq: 5000 # 5000
  eval_freq: 5000
  snapshot_freq_for_preemption: 10000
  weight: standard
  snapshot_sampling: true
  ema: 0.9999
  data_fraction: 1.0
data:
  train: deepstarr
  valid: deepstarr
  cache_dir: data
graph:
  type: uniform
  file: data
  report_all: false
noise:
  type: geometric
  sigma_min: 0.0001
  sigma_max: 20   # TRY THIS: 5-50 tried, all similar
sampling:
  predictor: euler
  steps: 128
  noise_removal: true
eval:
  batch_size: 256
  perplexity: false
  perplexity_batch_size: 32
# SP-MSE validation configuration
sp_mse_validation:
  enabled: false  # Set to true to enable SP-MSE validation during training
  validation_freq: 5000  # Frequency in training steps to run SP-MSE validation
  validation_samples: 1000  # Number of samples from validation set (0 = use all)
  oracle_path: /grid/koo/home/yiyu/scratch/D3-DNA-Discrete-Diffusion/model_zoo/deepstarr/oracle_models/oracle_DeepSTARR_DeepSTARR_data.ckpt  # Path to oracle model (auto-resolved if null)
  data_path: /grid/koo/home/yiyu/scratch/D3-DNA-Discrete-Diffusion/model_zoo/deepstarr/DeepSTARR_data.h5  # Path to dataset file (auto-resolved if null)
  sampling_steps: 249  # Number of sampling steps (auto-resolved if null)
  early_stopping_patience: null  # Stop training if no improvement for N validations (null = disabled)
optim:
  weight_decay: 1e-3   # note that it's int he 1e-1 order for pretraining; 1e-2 for fine tuning
  optimizer: AdamW
  lr: 0.0003     # TRY THIS
  beta1: 0.9     # TRY THIS: from diffusion
  beta2: 0.999   # TRY THIS: from diffusion
  eps: 1.0e-08
  warmup: 2500
  grad_clip: 1.0
model:
  name: small
  type: ddit
  architecture: transformer
  hidden_size: 768
  cond_dim: 128
  length: 249
  n_blocks: 12   # TRY THIS: ith Tran, 4 is min 
  n_heads: 12
  scale_by_sigma: false
  dropout: 0.4
wandb:
  enabled: true
  project: d3-ablation
  name: deepstarr-tran-sp-mse
  entity: d3-cshl
  tags: []
  notes: ""