defaults:
  - _self_
  - model: small
  - override hydra/launcher: submitit_slurm

# Wandb configuration
wandb_project: null  # Set to null by default, override via command line
wandb_name: null

ngpus: 1
tokens: 4
training:
  batch_size: 256
  accum: 1
  n_iters: 25600
  snapshot_freq: 5000
  log_freq: 100
  eval_freq: 500
  snapshot_freq_for_preemption: 1000
  weight: standard
  snapshot_sampling: true
  ema: 0.9999
data:
  train: c5_human_heart  # Options: combined_human_heart, generated_human_heart, human_heart, mpra
  valid: c5_human_heart
  cache_dir: data
graph:
  type: uniform
  file: data
  report_all: false
noise:
  type: geometric
  sigma_min: 0.0001
  sigma_max: 20
sampling:
  predictor: euler
  steps: 128
  noise_removal: true
eval:
  batch_size: 256
  perplexity: false
  perplexity_batch_size: 32
optim:
  weight_decay: 0
  optimizer: AdamW
  lr: 0.0003
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-08
  warmup: 2500
  grad_clip: 1.0
model:
  name: small
  type: ddit
  hidden_size: 768
  cond_dim: 256
  length: 200
  n_blocks: 12
  n_heads: 12
  scale_by_sigma: false
  dropout: 0.1

# Mode for 2-stage training
mode: pretraining  # Options: pretraining, fine-tuning


hydra:
  run:
    dir: exp_local/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: exp/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    max_num_timeout: 100000
    # timeout_min: 10079
    partition: g40x
    account: null
    mem_gb: 96
    cpus_per_task: 40
    gpus_per_node: ${ngpus}
    constraint: null
